services:
  - type: web
    name: campusconnect
    env: python
    region: oregon
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn campusconnect.wsgi --log-file -
    autoDeploy: true
